#include <stm32f407xx.h>
void USART1_Init(void)

{
  RCC->AHB1ENR|=RCC_AHB1ENR_GPIOAEN;
  RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
  GPIOA->MODER|=(2<<GPIO_MODER_MODE9_Pos);
  GPIOA->MODER|=(2<<GPIO_MODER_MODE10_Pos);
  USART1->BRR = 0x1117;
  GPIOA->AFR[1]|=(7<<GPIO_AFRH_AFSEL9_Pos); //af для PA9 tx
  GPIOA->AFR[1]|=(7<<GPIO_AFRH_AFSEL10_Pos); //af для PA10 rx
  USART1->CR1 |= USART_CR1_TE | USART_CR1_RE ;
  USART1->CR1 |= USART_CR1_UE;
  USART1->CR3|= USART_CR3_DMAT;
}